export const INGREDIENTS_REQUEST:'INGREDIENTS_REQUEST'= 'INGREDIENTS_REQUEST';
export const INGREDIENTS_SUCCESS:'INGREDIENTS_SUCCESS'= 'INGREDIENTS_SUCCESS';
export const INGREDIENTS_FAILED:'INGREDIENTS_FAILED'= 'INGREDIENTS_FAILED';

export const ADD_INGREDIENT_TO_CONSTRUCTOR:'ADD_INGREDIENT_TO_CONSTRUCTOR'= 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR:'REMOVE_INGREDIENT_FROM_CONSTRUCTOR'= 'REMOVE_INGREDIENT_FROM_CONSTRUCTOR';
export const REPLACE_CONSTRUCTOR_ITEM:'REPLACE_CONSTRUCTOR_ITEM'= 'REPLACE_CONSTRUCTOR_ITEM';

export const ORDER_REQUEST:'ORDER_REQUEST'= 'ORDER_REQUEST';
export const ORDER_SUCCESS:'ORDER_SUCCESS'= 'ORDER_SUCCESS';
export const ORDER_FAILED:'ORDER_FAILED'= 'ORDER_FAILED';
export const CLEAR_ORDER:'CLEAR_ORDER'= 'CLEAR_ORDER';

export const SWITCH_TAB:'SWITCH_TAB'= 'SWITCH_TAB';

export const FORGOT_PWD_REQUEST:'FORGOT_PWD_REQUEST'= 'FORGOT_PWD_REQUEST';
export const FORGOT_PWD_SUCCESS:'FORGOT_PWD_SUCCESS'= 'FORGOT_PWD_SUCCESS';
export const FORGOT_PWD_FAILED:'FORGOT_PWD_FAILED'= 'FORGOT_PWD_FAILED';

export const RESET_PWD_REQUEST:'RESET_PWD_REQUEST'= 'RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS:'RESET_PWD_SUCCESS'= 'RESET_PWD_SUCCESS';
export const RESET_PWD_FAILED:'RESET_PWD_FAILED'= 'RESET_PWD_FAILED';

export const REGISTER_REQUEST:'REGISTER_REQUEST'= 'REGISTER_REQUEST';
export const REGISTER_SUCCESS:'REGISTER_SUCCESS'= 'REGISTER_SUCCESS';
export const REGISTER_FAILED:'REGISTER_FAILED'= 'REGISTER_FAILED';

export const LOGIN_REQUEST:'LOGIN_REQUEST'= 'LOGIN_REQUEST';
export const LOGIN_SUCCESS:'LOGIN_SUCCESS'= 'LOGIN_SUCCESS';
export const LOGIN_FAILED:'LOGIN_FAILED'= 'LOGIN_FAILED'

export const LOGOUT_REQUEST:'LOGOUT_REQUEST'= 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS:'LOGOUT_SUCCESS'= 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED:'LOGOUT_FAILED'= 'LOGOUT_FAILED';

export const GET_USER_REQUEST:'GET_USER_REQUEST'= 'GET_USER_REQUEST';
export const GET_USER_SUCCESS:'GET_USER_SUCCESS'= 'GET_USER_SUCCESS';
export const GET_USER_FAILED:'GET_USER_FAILED'= 'GET_USER_FAILED';

export const UPDATE_USER_REQUEST:'UPDATE_USER_REQUEST'= 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS:'UPDATE_USER_SUCCESS'= 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED:'UPDATE_USER_FAILED'= 'UPDATE_USER_FAILED';

export const REFRESH_TOKEN_REQUEST:'REFRESH_TOKEN_REQUEST'= 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS:'REFRESH_TOKEN_SUCCESS'= 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED:'REFRESH_TOKEN_FAILED'= 'REFRESH_TOKEN_FAILED';